### PR TITLE
Add support for TensorBoard.

### PR DESCRIPTION
**Pull request by krasin**
Export accuracy at every epoch.
The data for TensorBoard is saved in logs/ subdirectory.

### CODE REVIEW

**Comment by krasin** [comment]
This is how it looks like in TensorBoard: http://imgur.com/TvDsfLK

**Comment by rinuboney** [comment]
why ```python tensorflow/tensorboard/tensorboard.py --logdir=path/to/ladder/logs```? why not ```tensorboard --logdir=path/to/ladder/logs```? Also, now it doesn't write the accuracy properly to log file. It should be ```log_i = [epoch_n, cur_accuracy]```. It would be better if you can make the changes and test it.

Actually, what is the advantage of adding support for TensorBoard to plot the accuracy when the accuracy is already available in the log file? If required, it is fairly easy to plot the data from the log file.

**Comment by krasin** [comment]
Hi Rinu,

I will address your comments when I am back to home. All reasonable.

As for the advantage of adding support for TensorBoard, I would only think of one, really: TensorBoard is the standard visualization tool in TensorFlow, most of the people will likely be aware of it, while only few will have the tools to visualize CSV graphs at their hand. It's not super important, feel free to avoid increasing the complexity of the code.

**Comment by krasin** [comment]
It looks like I didn't have time today, and there're no particular interest.
I will close the pull request, but it will be trivial to recreate if needed.

**Pull request closed without merging**
